/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesNewIndexRouteImport } from './routes/recipes/new/index'
import { Route as RecipesSlugIndexRouteImport } from './routes/recipes/$slug/index'
import { Route as RecipesIdIndexRouteImport } from './routes/recipes/$id/index'
import { Route as CategoriesSlugIndexRouteImport } from './routes/categories/$slug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewIndexRoute = RecipesNewIndexRouteImport.update({
  id: '/recipes/new/',
  path: '/recipes/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugIndexRoute = RecipesSlugIndexRouteImport.update({
  id: '/recipes/$slug/',
  path: '/recipes/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdIndexRoute = RecipesIdIndexRouteImport.update({
  id: '/recipes/$id/',
  path: '/recipes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugIndexRoute = CategoriesSlugIndexRouteImport.update({
  id: '/categories/$slug/',
  path: '/categories/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/recipes/$slug': typeof RecipesSlugIndexRoute
  '/recipes/new': typeof RecipesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/recipes/$slug': typeof RecipesSlugIndexRoute
  '/recipes/new': typeof RecipesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories/$slug/': typeof CategoriesSlugIndexRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
  '/recipes/$slug/': typeof RecipesSlugIndexRoute
  '/recipes/new/': typeof RecipesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories/$slug'
    | '/recipes/$id'
    | '/recipes/$slug'
    | '/recipes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories/$slug'
    | '/recipes/$id'
    | '/recipes/$slug'
    | '/recipes/new'
  id:
    | '__root__'
    | '/'
    | '/categories/$slug/'
    | '/recipes/$id/'
    | '/recipes/$slug/'
    | '/recipes/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesSlugIndexRoute: typeof CategoriesSlugIndexRoute
  RecipesIdIndexRoute: typeof RecipesIdIndexRoute
  RecipesSlugIndexRoute: typeof RecipesSlugIndexRoute
  RecipesNewIndexRoute: typeof RecipesNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new/': {
      id: '/recipes/new/'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug/': {
      id: '/recipes/$slug/'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/': {
      id: '/recipes/$id/'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug/': {
      id: '/categories/$slug/'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesSlugIndexRoute: CategoriesSlugIndexRoute,
  RecipesIdIndexRoute: RecipesIdIndexRoute,
  RecipesSlugIndexRoute: RecipesSlugIndexRoute,
  RecipesNewIndexRoute: RecipesNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
